image: python:3.8.3-slim

before_script:
#  - apt-get update -qq && apt-get install -y -qq python3
  - python3 --version
  - which python3

stages:
  - test

test_a:
  stage: test
  script:
    - ./unit-test.sh


